export const menuItemsData = [
    {
      id: 1,
      category: 'veg',
      name: 'Dosa',
      info: 'thin, spicy, crispy crepe-like food made from fermented rice',
      price: 112,
      img: '/images/dosa.jpg',
    },
    {
      id: 2,
      name: 'Spiced Corn and Rice Pilaf',
      category: 'veg',
      info: 'spicey with cumin and then corn to give unique Indian flavor',
      price: 149,
      img: '/images/corn.jpg',
    },
    {
      id: 3,
      name: 'Pizza',
      category: 'nonveg',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 330,
      img: '/images/pizza.jpg',
    },
    {
      id: 4,
      name: 'white sauce pasta',
      category: 'veg',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 159,
      img: '/images/bowl3.png',
    },
    {
      id: 5,
      name: 'Broccoli Partha',
      category: 'veg',
      info: 'a healthy and tasty version of the paratha, the add broccoli to it and make it non-oily ',
      price: 24,
      img: '/images/paratha.jpg',
    },
    {
      id: 6,
      name: 'Idli',
      category: 'veg',
      info: 'soft, pillowy steamed savory cake made from rice and lentil batter',
      price: 69,
      img: '/images/Idli.jpg',
    },
    {
      id: 7,
      name: 'Vada',
      category: 'veg',
      info: 'crispy, fluffy, soft and delicious lentil fritters ',
      price: 69,
      img: '/images/vada.jpg',
    },
    {
      id: 8,
      name: 'poha',
      category: 'veg',
      info: 'Made with onions, potatoes and seasoning like chillies, crushed peanuts, lemon and curry leaves make up a tasty',
      price: 49,
      img: '/images/poha.jpg',
    },
    {
      id: 9,
      name: 'Keema Kulcha',
      category: 'nonveg',
      info: 'Chicken keema is cooked along with dry spice powders and then combined with cheese and stuffed in a kulcha',
      price: 119,
      img: '/images/kulcha.jpeg',
    },
    {
      id: 10,
      name: 'Hakka Noodles',
      category: 'nonveg',
      info: 'Chinese food with the use of Indian spices with dishes like Chilli Chicken.',
      price: 219,
      img: '/images/noodles.jpg',
    },
    {
      id: 11,
      name: 'Chickn Biriyani',
      category: 'nonveg',
      info: 'chicken marinated in yogurt, chile powder, and garam and biriyani masala layered with fragrant, spiced basmati rice, and caramelized onions.',
      price: 320,
      img: '/images/biriyani.jpg',
    },
    {
      id: 12,
      name: 'Chilli chicken',
      category: 'nonveg',
      info: ' Succulent chicken coated in a thick batter and fried until crisp are added to a garlicky chilli luscious gravy',
      price: 289,
      img: '/images/chilli.jpg',
    },
    {
      id: 13,
      name: 'Aloo Tikki Chaat',
      category: 'veg',
      info: 'fried potato patties are topped with a tangy-sweet tamarind chutney and spicy green chutney along with curd',
      price: 89,
      img: '/images/Aloo.jpg',
    },
    {
      id: 14,
      name: 'Golgappa',
      category: 'veg',
      info: 'a round and flaky ‘crepe’, made out of ‘sooji’ or semolina and with a gentle prod of his thumb, carved a hole in the center of it',
      price: 49,
      img: '/images/golgappa.jpg',
    },
    {
      id: 15,
      name: 'Gajar Ka Halwa',
      category: 'veg',
      info: 'grated carrots in a pot containing a specific amount of water, milk and sugar, cardamom and then cooking while stirring regularly',
      price: 79,
      img: '/images/Gajar.jpg',
    },
    {
      id: 16,
      name: 'Gulap-Jamun',
      category: 'veg',
      info: 'a berry-sized ball dunken in rose flavoured sugar syrup',
      price: 59,
      img: '/images/gulab-jamun.jpg',
    },
    
  ];
